---
title: "xmsPANDA_getting_started"
output:
  html_document:
    toc: true
date: "2023-10-31"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# This Notebook includes steps for installing xmsPANDA v1.4.0 and it's dependencies. v1.4.0 of xmsPANDA includes updates to make it compatible with R 4.0 and higher. 

## Install dependencies - run only if necessary and set eval=TRUE


```{r, echo=FALSE,eval=FALSE}
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

Sys.setenv(R_REMOTES_NO_ERRORS_FROM_WARNINGS="true")
BiocManager::install(update = FALSE)

BiocManager::install(c("mixOmics","CMA","GO.db","impute","limma","qvalue","pcaMethods","KEGGREST","genefilter",
                       "BiocParallel","KEGGgraph","Rgraphviz","edgeR","formatR","graph"),suppressUpdates=TRUE,dependencies=TRUE)

install.packages(c('rgl', 'snow', 'doSNOW', 'foreach', 'e1071', 'WGCNA','reshape2','robust','mvoutlier',
'randomForest', 'party', 'fdrtool', 'GeneNet', 'corpcor', 'earth',
'pROC', 'multcomp', 'pls', 'plsgenomics', 'igraph', 'ROCR',
'flashClust', 'data.table', 'dplyr', 'mclust', 'RankAggreg', 'pamr', "tidyverse","grid",
'sandwich', 'Boruta', 'lsmeans', 'car', 'ggpubr', 'extrafont', 'stepPlr', 'h2o','shinyBS', 'V8', 'shinyWidgets', 
                   'plotly','shinycssloaders', 'colourpicker',"raster","ROSE","devtools",
"lambda.r","formatR","futile.logger","futile.options","gmm"),dependencies=TRUE,
                 repos="https://cran.r-project.org")


Sys.setenv(R_REMOTES_NO_ERRORS_FROM_WARNINGS="true")
library(devtools); install_github("kuppal3gt/xmsPANDA-R4.0")

```


## Launch the Shiny App 

```{r,echo=FALSE}
#launch xmsPANDA
suppressPackageStartupMessages(library(xmsPANDA))

#run the Lite version
runApp.xmsPANDALite()

#OR run the full version
#runApp.xmsPANDA()

```

## Running the sample script for two-class classification

```{r, echo=FALSE}

feature_table_file<-"https://raw.githubusercontent.com/kuppal3gt/xmsPANDA-R4.0/main/inst/shinyapp/example_data/exh1n1_metabolome.txt"
class_labels_file<-"https://raw.githubusercontent.com/kuppal3gt/xmsPANDA-R4.0/main/inst/shinyapp/example_data/exh1n1_classlabels.txt"
outloc<-paste0(getwd(),"/xmsPANDAliteout/")


Xmat<-read.table(feature_table_file,sep="\t",header=TRUE,stringsAsFactors = FALSE,check.names = FALSE)
Ymat<-read.table(class_labels_file,sep="\t",header=TRUE,stringsAsFactors = FALSE,check.names = FALSE)


#limma
demetabs_reslite1<-diffexp.lite(Xmat=Xmat,Ymat=Ymat,outloc=outloc,featselmethod="limma",normalization.method = "log2transform",
                                pvalue.thresh = 0.05,fdrthresh=0.1,fdrmethod="BH",foldchangethresh = 0)

#pls
demetabs_reslite2<-diffexp.lite(Xmat=Xmat,Ymat=Ymat,outloc=outloc,featselmethod="pls",normalization.method = "log2transform",pls_vip_thresh=2,foldchangethresh = 0)


#find common features selected by limma and pls
demetabs_reslite_1and2<-merge(demetabs_reslite1$diffexp_metabs[,c("Name","P.value","adjusted.P.value")],demetabs_reslite2$diffexp_metabs,by=c("Name"))


```
